---
# tasks file for ambari-server
  - name: name of the variable is
    debug:
     msg: 'name of the var is {{ as }}'
  - name: installing ambari-server
    zypper: name="{{ as }}" state=installed
  - name: setting up ambari server
    shell: "ambari-server setup -s" 
    args: 
     executable: /bin/bash
  - name: starting the service for ambari
    service: name="{{ as }}" state=restarted enabled=on
  - name: cheking if ambari is up
    wait_for: port=8080 host=127.0.0.1 delay=10 
